name: Auto Build Recognition Image with "AWS" tag

on:
  push:
    branches: master

jobs:
  recognition-aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./recognition/Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: |
            irad1994/recognition:aws
          cache-from: type=registry,ref=irad1994/recognition:aws
          cache-to: type=inline
